steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ml-engineer-playground/nlp-my-image', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml-engineer-playground/nlp-my-image']
images:
- gcr.io/ml-engineer-playground/nlp-my-image
